name = "pushout_boolean_algebras"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["pushout_boolean_algebras"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Utils"

[[lean_exe]]
name = "pushout_boolean_algebras"
root = "Main"
default = true
